@token =  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTcwMDY5Njc1NCwiZXhwIjoxNzAwNzMyNzU0fQ.81UwOG2SgJoYZ5zxx-aQTr_GAFbquOVfiGqvPFdUigU

###
#회원가입
POST http://localhost:3010/api/register HTTP/1.1
Content-Type: application/json

{
  "name": "오이333",
  "email": "2alp2222211onf@naver.com",
  "password": "123123",
  "passwordRe": "123123",
  "description": ""
}



###

#회원 로그인

# @name getJWT
POST http://localhost:3010/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "2alp2222211onf@naver.com",
  "password": "123123"
}



###

#회원 로그아웃
GET http://localhost:3010/api/auth/logout HTTP/1.1
Content-Type: application/json
authorization: {{getJWT.response.body.message}}



###

#회원 탈퇴
DELETE  http://localhost:3010/api/user/2 HTTP/1.1
Content-Type: application/json
authorization: {{token}}




###

#회원정보 조회
GET http://localhost:3010/api/user/76 HTTP/1.1
Content-Type: application/json
authorization: {{getJWT.response.body.message}}



###

#회원정보 수정
PATCH http://localhost:3010/api/users/3 HTTP/1.1
Content-Type: application/json
authorization: {{getJWT.response.body.message}}
# authorization: {{token}}

{
  "name": "ㄹㄹ",
  "email": "modify@navder.com",
  "password": "ddd ddd",
  "passwordRe": "ddd ddd",
  "description": "떡볶이를 좋아해요~"
}



###
#게시물 삭제
DELETE  http://localhost:3010/api/post/11 HTTP/1.1
Content-Type: application/json
authorization: {{token}}



#

###
#게시물 작성
POST  http://localhost:3010/api/post HTTP/1.1
Content-Type: application/json
authorization: {{getJWT.response.body.message}}

{
  "title": "코고는 고양이",
  "content": "빌리는 잘때 코골아요",
  "category": "cat",
  "petName": "빌리"
}

#


