#회원 로그인

# @name getJWT
POST http://localhost:3010/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "aaaaap@naver.com",
  "password": "poiwnl87365"
}

### 댓글 작성
POST http://localhost:3010/api/comment/11 HTTP/1.1
Content-Type: application/json
authorization: {{getJWT.response.body.message}}

{
  "content":"중간이에요"
}

### 댓글 조회
GET http://localhost:3010/api/post/11 HTTP/1.1
Content-Type: application/json
authorization: {{getJWT.response.body.message}}

### 댓글 수정
PUT http://localhost:3010/api/comment/7 HTTP/1.1
Content-Type: application/json
authorization: {{getJWT.response.body.message}}

{
  "content":"별로에요"
}

### 댓글 삭제
DELETE  http://localhost:3010/api/comment/9 HTTP/1.1
Content-Type: application/json
authorization: {{getJWT.response.body.message}}


